"""
Reading SVRL — the output side of Schematron.

WHAT SVRL IS
------------
Schematron Validation Report Language. When you run a compiled Schematron rule set
over a document, this is what comes back. It is standardised (ISO/IEC 19757-3), so
every Schematron processor emits the same shape — which is why sahih can support
EN 16931, PINT, and jurisdiction rule sets through one parser.

THE THREE ELEMENTS THAT MATTER
------------------------------
``<svrl:fired-rule>``
    A rule whose precondition matched, so it was evaluated. Emitted whether or not
    the rule then passed. Counting these tells you how much of the rule set actually
    applied to this document.

``<svrl:failed-assert>``
    An ``<assert>`` that evaluated FALSE. This is a violation. The overwhelming
    majority of findings are these.

``<svrl:successful-report>``
    A ``<report>`` that evaluated TRUE. Confusingly, this is *also* a finding.
    Schematron has two rule forms — ``assert`` fires when its test is false,
    ``report`` fires when its test is true. Authors use ``report`` to flag
    "this situation is present and you should know about it".

    Miss this element and you silently drop real findings. Several validators do.
"""

from __future__ import annotations

from defusedxml import ElementTree as DefusedET

from .models import Finding, Severity, ValidationReport

# The SVRL namespace, as an ElementTree "{uri}tag" prefix.
SVRL_NS = "{http://purl.oclc.org/dsdl/svrl}"

FAILED_ASSERT = f"{SVRL_NS}failed-assert"
SUCCESSFUL_REPORT = f"{SVRL_NS}successful-report"
FIRED_RULE = f"{SVRL_NS}fired-rule"
TEXT = f"{SVRL_NS}text"

#: Both element types represent "a rule produced a finding".
FINDING_ELEMENTS = (FAILED_ASSERT, SUCCESSFUL_REPORT)


def _clean(text: str | None) -> str:
    """
    Collapse whitespace in rule text.

    Rule messages are authored inside XML and arrive full of newlines and indentation
    from the source Schematron. Nobody wants that in a CLI table or a JSON payload.
    """
    return " ".join((text or "").split())


def _rule_id(element) -> str:
    """
    Pull the rule identifier.

    Rule sets are inconsistent here: some put it on ``id``, some on ``flag``-adjacent
    attributes, and a few omit it. When it is genuinely absent we return a marker
    rather than an empty string, so it is obvious in output that the rule set is at
    fault rather than the parser.
    """
    return element.get("id") or element.get("name") or "(unidentified-rule)"


def parse_svrl(
    svrl_xml: str | bytes,
    *,
    ruleset: str = "",
    source: str = "",
) -> ValidationReport:
    """
    Turn an SVRL document into a `ValidationReport`.

    Args:
        svrl_xml: The SVRL produced by a Schematron run.
        ruleset:  Label for which rule set produced this, e.g. ``"PINT-AE 2026.5"``.
                  Carried onto every finding so stacked results stay attributable.
        source:   Label for the validated document, usually a filename.

    Returns:
        A `ValidationReport`. An SVRL document with no findings yields an empty,
        valid report — that is a normal result, not an error.

    Raises:
        SVRLParseError: If the input is not parseable XML.

    Note on safety: parsing goes through ``defusedxml``. SVRL is generated by our own
    processor rather than supplied by a counterparty, so the risk here is lower than
    at the invoice boundary — but a uniform rule ("all XML parsing in this library is
    defused") is far easier to keep correct than a per-call judgement call.
    """
    if isinstance(svrl_xml, str):
        svrl_xml = svrl_xml.encode("utf-8")

    try:
        root = DefusedET.fromstring(svrl_xml)
    except Exception as exc:  # defusedxml raises several distinct types
        raise SVRLParseError(f"Could not parse SVRL output: {exc}") from exc

    findings: list[Finding] = []
    fired = 0

    # One pass over the tree. SVRL nests findings under <fired-rule> siblings rather
    # than children, so a flat iteration is both correct and simpler than descending.
    for element in root.iter():
        tag = element.tag

        if tag == FIRED_RULE:
            fired += 1
            continue

        if tag in FINDING_ELEMENTS:
            text_el = element.find(TEXT)
            findings.append(
                Finding(
                    rule_id=_rule_id(element),
                    severity=Severity.from_svrl(element.get("flag")),
                    message=_clean(text_el.text if text_el is not None else ""),
                    location=element.get("location", ""),
                    test=element.get("test", ""),
                    ruleset=ruleset,
                )
            )

    return ValidationReport(
        findings=tuple(findings),
        fired_rules=fired,
        ruleset=ruleset,
        source=source,
    )


class SVRLParseError(Exception):
    """Raised when SVRL output cannot be parsed at all."""
